version: "3.7"

services:
  dislinkt-fe:
    container_name: dislinkt-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    networks:
      - network-for-ms

networks:
  network-for-ms:
    name: network-for-ms